[workspace]
members = [
	"client/cli",
	"client/consensus/aura",
	"client/consensus/common",
	"client/consensus/relay-chain",
	"client/network",
	"client/pov-recovery",
	"client/service",
	"pallets/aura-ext",
	"pallets/collator-selection",
	"pallets/dmp-queue",
	"pallets/parachain-system",
	"pallets/parachain-system/proc-macro",
	"pallets/session-benchmarking",
	"pallets/xcm",
	"pallets/xcmp-queue",
	"primitives/core",
	"primitives/parachain-inherent",
	"primitives/timestamp",
	"primitives/utility",
	"polkadot-parachains/",
	"polkadot-parachains/pallets/parachain-info",
	"polkadot-parachains/pallets/ping",
	"polkadot-parachains/rococo",
	"polkadot-parachains/shell",
	"polkadot-parachains/statemint-common",
	"polkadot-parachains/statemint",
	"polkadot-parachains/statemine",
	"polkadot-parachains/westmint",
	"test/runtime",
	"test/runtime-upgrade",
	"test/client",
	"test/service",
	"test/relay-sproof-builder",
	"test/relay-validation-worker-provider",
]

[profile.release]
panic = "unwind"
[patch."https://github.com/paritytech/polkadot"]
polkadot-cli ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-pvf ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-core-primitives ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-parachain ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
test-parachain-adder ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
test-parachain-halt ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-service ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
kusama-runtime ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
pallet-xcm ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
xcm ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
xcm-executor ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-primitives ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-runtime-common ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-runtime-parachains ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
slot-range-helper ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
xcm-builder ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-approval-distribution ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-network-protocol ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-jaeger ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-primitives ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-statement-table ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-subsystem ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-subsystem-types ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-overseer-gen ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
metered-channel ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-overseer-gen-proc-macro ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-subsystem-test-helpers ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-subsystem-util ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-metrics ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-overseer ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-overseer-all-subsystems-gen ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-availability-bitfield-distribution ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-availability-distribution ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-erasure-coding ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-runtime-api ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-availability-recovery ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-client ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-runtime ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
rococo-runtime ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
bp-messages ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
bp-runtime ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
bp-rococo ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
bp-polkadot-core ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
bp-wococo ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
bridge-runtime-common ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
bp-message-dispatch ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
pallet-bridge-dispatch ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
pallet-bridge-grandpa ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
bp-header-chain ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
bp-test-utils ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
pallet-bridge-messages ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
bp-rialto ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
westend-runtime ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-collator-protocol ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-dispute-distribution ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-gossip-support ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-network-bridge ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-collation-generation ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-approval-voting ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-av-store ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-backing ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-bitfield-signing ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-candidate-validation ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-chain-api ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-parachains-inherent ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-provisioner ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-rpc ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-statement-distribution ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-test-client ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-test-runtime ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-test-service ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-chain-selection ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-dispute-coordinator ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-node-core-dispute-participation ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-test-malus ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-simnet ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-simnet-node ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot-simnet-test ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
test-parachains ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
test-parachain-adder-collator ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
staking-miner ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
polkadot ={git = "https://github.com/apopiak/polkadot.git" ,branch = "apopiak/asset-not-found" }
